/*
 * _titlecase-lexicon.mjs — GENERATED, do not edit by hand.
 * ===========================================================================
 * VENDORED from the site repo's lit/_scraper/_titlecase-lexicon.mjs — keep in
 * sync with it, exactly like _entities.mjs.
 *
 * Regenerate with (in the site repo):  node lit/_scraper/build-titlecase-lexicon.mjs
 * (then re-vendor into the three lit-data-abs* shard repos, like _entities.mjs)
 *
 * The words and multi-word names that must KEEP their capitals when
 * sentenceCaseTitle rewrites an ALL-CAPS deposited title into sentence case —
 * acronyms (DNA, CAPM, ANOVA) and proper nouns (Bayesian, Cournot, Drosophila).
 * Mined from the 714962 properly-cased titles and 306000 abstracts in the
 * catalog; see build-titlecase-lexicon.mjs for how the evidence is filtered.
 * Anything NOT listed here is lowercased, which is the sentence-case default.
 * ===========================================================================
 */

// lowercase word -> the form to restore.
export const TITLECASE_WORDS = {
  "1b": "1B",
  "2d": "2D",
  "2sls": "2SLS",
  "3pl": "3PL",
  "3sls": "3SLS",
  "4d": "4D",
  "aaa": "AAA",
  "aacsb": "AACSB",
  "ac": "AC",
  "academy": "Academy",
  "ace": "ACE",
  "aces": "ACES",
  "achilles": "Achilles",
  "adam": "Adam",
  "adams": "Adams",
  "adr": "ADR",
  "aea": "AEA",
  "aer": "AER",
  "afa": "AFA",
  "africa": "Africa",
  "africa's": "Africa's",
  "african": "African",
  "africa’s": "Africa’s",
  "ag": "AG",
  "agora": "Agora",
  "agv": "AGV",
  "ahp": "AHP",
  "ai": "AI",
  "aia": "AIA",
  "aicpa": "AICPA",
  "aiyagari": "Aiyagari",
  "ajzen's": "Ajzen's",
  "akron": "Akron",
  "alabama": "Alabama",
  "alan": "Alan",
  "alaska": "Alaska",
  "alaskan": "Alaskan",
  "albert": "Albert",
  "alchian": "Alchian",
  "alchian's": "Alchian's",
  "aleksander": "Aleksander",
  "alex": "Alex",
  "alexander": "Alexander",
  "allais": "Allais",
  "alleghany": "Alleghany",
  "allen": "Allen",
  "almon's": "Almon's",
  "alonso's": "Alonso's",
  "am": "AM",
  "america": "America",
  "america's": "America's",
  "american": "American",
  "americans": "Americans",
  "amex": "AMEX",
  "amj": "AMJ",
  "amr": "AMR",
  "amsterdam": "Amsterdam",
  "anders": "Anders",
  "andhra": "Andhra",
  "andreas": "Andreas",
  "angeles": "Angeles",
  "anglo": "Anglo",
  "anglos": "Anglos",
  "ann": "Ann",
  "anova": "ANOVA",
  "antioch": "Antioch",
  "apache": "Apache",
  "apl": "APL",
  "april": "April",
  "arab": "Arab",
  "arabic": "Arabic",
  "arb": "ARB",
  "arbor's": "Arbor's",
  "arch": "ARCH",
  "argentina": "Argentina",
  "argyris": "Argyris",
  "arizona": "Arizona",
  "arizona's": "Arizona's",
  "armen": "Armen",
  "army": "Army",
  "arrow": "Arrow",
  "arrow's": "Arrow's",
  "arthur": "Arthur",
  "ashland": "Ashland",
  "asia": "Asia",
  "asian": "Asian",
  "asq": "ASQ",
  "assa": "ASSA",
  "association's": "Association's",
  "athens": "Athens",
  "atlanta": "Atlanta",
  "atlantic": "Atlantic",
  "atm": "ATM",
  "atm's": "ATM's",
  "august": "August",
  "australia": "Australia",
  "australian": "Australian",
  "austria": "Austria",
  "austria's": "Austria's",
  "austrian": "Austrian",
  "autocode": "AutoCode",
  "autumn": "Autumn",
  "averch": "Averch",
  "ayres": "Ayres",
  "azotobacter": "Azotobacter",
  "b2b": "B2B",
  "bacillus": "Bacillus",
  "bakke": "Bakke",
  "balassa": "Balassa",
  "baldrige": "Baldrige",
  "banach": "Banach",
  "bangladesh": "Bangladesh",
  "bangladeshi": "Bangladeshi",
  "barnard": "Barnard",
  "baroque": "Baroque",
  "bauerschmidt": "Bauerschmidt",
  "baumol": "Baumol",
  "baumol's": "Baumol's",
  "bayesian": "Bayesian",
  "becker": "Becker",
  "beer's": "Beer's",
  "beijing": "Beijing",
  "bela": "Bela",
  "belarus": "Belarus",
  "belgian": "Belgian",
  "belgium": "Belgium",
  "bengal": "Bengal",
  "benjamin": "Benjamin",
  "bergson": "Bergson",
  "berkeley": "Berkeley",
  "bernoulli": "Bernoulli",
  "bertrand": "Bertrand",
  "betti": "Betti",
  "beveridge": "Beveridge",
  "bewley": "Bewley",
  "bhopal": "Bhopal",
  "bible": "Bible",
  "biddle": "Biddle",
  "bihar": "Bihar",
  "bing": "Bing",
  "bitcoin": "Bitcoin",
  "blau's": "Blau's",
  "bloomberg": "Bloomberg",
  "bm": "BM",
  "bma": "BMA",
  "boldrin": "Boldrin",
  "bolivia": "Bolivia",
  "bonn": "Bonn",
  "bonoma": "Bonoma",
  "booker": "Booker",
  "boolean": "Boolean",
  "bops": "BOPS",
  "borda": "Borda",
  "bose": "Bose",
  "boston": "Boston",
  "bowen": "Bowen",
  "bowley": "Bowley",
  "boynton": "Boynton",
  "bradford": "Bradford",
  "brazil": "Brazil",
  "brazil's": "Brazil's",
  "brazilian": "Brazilian",
  "breeden": "Breeden",
  "brexit": "Brexit",
  "brian": "Brian",
  "britain": "Britain",
  "britain's": "Britain's",
  "british": "British",
  "bsdes": "BSDEs",
  "buchanan": "Buchanan",
  "buckner": "Buckner",
  "bulletin": "Bulletin",
  "bundesbank": "Bundesbank",
  "bundesliga": "Bundesliga",
  "bureau": "Bureau",
  "burma": "Burma",
  "burrows": "Burrows",
  "cadbury": "Cadbury",
  "cagan": "Cagan",
  "calcutta": "Calcutta",
  "california": "California",
  "california's": "California's",
  "california’s": "California’s",
  "calvo": "Calvo",
  "campbell": "Campbell",
  "canada": "Canada",
  "canada's": "Canada's",
  "canadian": "Canadian",
  "capm": "CAPM",
  "caribbean": "Caribbean",
  "carleton": "Carleton",
  "carlo": "Carlo",
  "carlson": "Carlson",
  "carnegie": "Carnegie",
  "carolina": "Carolina",
  "carp": "CARP",
  "cartesian": "Cartesian",
  "catholic": "Catholic",
  "catv": "CATV",
  "cauchy": "Cauchy",
  "cavalcanti": "Cavalcanti",
  "cayley": "Cayley",
  "cbi": "CBI",
  "cee": "CEE",
  "centaurus": "Centaurus",
  "ceo": "CEO",
  "ceos": "CEOs",
  "ceos'": "CEOs'",
  "ceos’": "CEOs’",
  "cesaro": "Cesaro",
  "ceylon": "Ceylon",
  "chadwick": "Chadwick",
  "chancery": "Chancery",
  "charlotte": "Charlotte",
  "cheung": "Cheung",
  "chicago": "Chicago",
  "chile": "Chile",
  "chile's": "Chile's",
  "chilean": "Chilean",
  "china": "China",
  "china's": "China's",
  "china’s": "China’s",
  "chinese": "Chinese",
  "chipman": "Chipman",
  "chlamydomonas": "Chlamydomonas",
  "chlorella": "Chlorella",
  "christmas": "Christmas",
  "christopher": "Christopher",
  "chromatium": "Chromatium",
  "chung": "Chung",
  "cincinnati": "Cincinnati",
  "cis": "CIs",
  "clara": "Clara",
  "clarence": "Clarence",
  "clark": "Clark",
  "cleveland": "Cleveland",
  "coase": "Coase",
  "coasian": "Coasian",
  "cobb": "Cobb",
  "cochrane": "Cochrane",
  "cof": "COF",
  "cole": "Cole",
  "colombia": "Colombia",
  "colorado": "Colorado",
  "columbia": "Columbia",
  "commission's": "Commission's",
  "compustat": "Compustat",
  "condorcet": "Condorcet",
  "congo": "Congo",
  "congress": "Congress",
  "connecticut": "Connecticut",
  "conwip": "CONWIP",
  "cooper": "Cooper",
  "cops": "CoPS",
  "corps": "Corps",
  "council": "Council",
  "cournot": "Cournot",
  "cournot's": "Cournot's",
  "covid": "COVID",
  "cox": "Cox",
  "cpa": "CPA",
  "cpm": "CPM",
  "cresse": "CRESSE",
  "crsp": "CRSP",
  "cuba": "Cuba",
  "cummins": "Cummins",
  "cvp": "CVP",
  "czechoslovakia": "Czechoslovakia",
  "côte": "Côte",
  "d": "D",
  "daimler": "Daimler",
  "daniel": "Daniel",
  "danish": "Danish",
  "danny": "Danny",
  "darby": "Darby",
  "darwinian": "Darwinian",
  "dc": "DC",
  "ddb": "DDB",
  "dea": "DEA",
  "dearing": "Dearing",
  "december": "December",
  "dein": "Dein",
  "delaware": "Delaware",
  "demsetz": "Demsetz",
  "denmark": "Denmark",
  "denver": "Denver",
  "descartes": "Descartes",
  "deutsche": "Deutsche",
  "dickey": "Dickey",
  "dickinson": "Dickinson",
  "diebold": "Diebold",
  "diego": "Diego",
  "diptera": "Diptera",
  "dirichlet": "Dirichlet",
  "disney": "Disney",
  "disneyland": "Disneyland",
  "divisia": "Divisia",
  "dna": "DNA",
  "dominion": "Dominion",
  "douglas": "Douglas",
  "dr": "Dr",
  "drosophila": "Drosophila",
  "dsge": "DSGE",
  "dss": "DSS",
  "durbin": "Durbin",
  "durkheim": "Durkheim",
  "dutch": "Dutch",
  "dwyer": "Dwyer",
  "earth": "Earth",
  "east": "East",
  "eaton": "Eaton",
  "ec": "EC",
  "econ": "Econ",
  "ecr": "ECR",
  "edgeworth": "Edgeworth",
  "edi": "EDI",
  "edison": "Edison",
  "edp": "EDP",
  "edward": "Edward",
  "edwin": "Edwin",
  "efa": "EFA",
  "egypt": "Egypt",
  "einstein's": "Einstein's",
  "elliott": "Elliott",
  "elton": "Elton",
  "emq": "EMQ",
  "ems": "EMS",
  "emu": "EMU",
  "engel": "Engel",
  "engels": "Engels",
  "england": "England",
  "engle": "Engle",
  "english": "English",
  "eoq": "EOQ",
  "erlang's": "Erlang's",
  "erm": "ERM",
  "escherichia": "Escherichia",
  "ethiopia": "Ethiopia",
  "ethiopian": "Ethiopian",
  "eu": "EU",
  "euclidean": "Euclidean",
  "euler": "Euler",
  "euler's": "Euler's",
  "eurasian": "Eurasian",
  "eurobond": "Eurobond",
  "eurocurrency": "Eurocurrency",
  "eurodollar": "Eurodollar",
  "europe": "Europe",
  "europe's": "Europe's",
  "european": "European",
  "europeans": "Europeans",
  "euv": "EUV",
  "exsec's": "ExSec's",
  "fang": "Fang",
  "favar": "FAVAR",
  "fbbva": "FBBVA",
  "fbi": "FBI",
  "fdi": "FDI",
  "fearon": "Fearon",
  "february": "February",
  "febs": "FEBS",
  "fellowship": "Fellowship",
  "fels": "Fels",
  "fermat": "Fermat",
  "fernando": "Fernando",
  "fes": "FeS",
  "fha": "FHA",
  "fhlb": "FHLB",
  "fhlbb": "FHLBB",
  "fiedler's": "Fiedler's",
  "fieller's": "Fieller's",
  "fifa": "FIFA",
  "finnish": "Finnish",
  "fishburn's": "Fishburn's",
  "fisher": "Fisher",
  "flac": "FLAC",
  "florida": "Florida",
  "fm": "FM",
  "fma": "FMA",
  "fmn": "FMN",
  "fms": "FMS",
  "fomc": "FOMC",
  "ford": "Ford",
  "fortieth": "Fortieth",
  "fortran": "FORTRAN",
  "fortune": "Fortune",
  "fortune's": "Fortune's",
  "fourier": "Fourier",
  "fox": "Fox",
  "france": "France",
  "francisco": "Francisco",
  "frank": "Frank",
  "franklin": "Franklin",
  "frederick": "Frederick",
  "freemasonry": "Freemasonry",
  "french": "French",
  "friedman": "Friedman",
  "friedman's": "Friedman's",
  "frisch": "Frisch",
  "froeb": "Froeb",
  "ftc": "FTC",
  "function1": "Function1",
  "g": "G",
  "galatea": "Galatea",
  "gallatin": "Gallatin",
  "garch": "GARCH",
  "gary": "Gary",
  "gatb": "GATB",
  "gatsby": "Gatsby",
  "gauss": "Gauss",
  "gaussian": "Gaussian",
  "gdp": "GDP",
  "gdss": "GDSS",
  "george": "George",
  "georgescu": "Georgescu",
  "german": "German",
  "germany": "Germany",
  "gert": "GERT",
  "gesell": "Gesell",
  "gfa": "GFA",
  "ghana": "Ghana",
  "gibrat's": "Gibrat's",
  "gibson": "Gibson",
  "giddens": "Giddens",
  "giffen": "Giffen",
  "gimbel": "Gimbel",
  "gis": "GIS",
  "glasgow": "Glasgow",
  "glueck": "Glueck",
  "gmm": "GMM",
  "gnp": "GNP",
  "god": "God",
  "god's": "God's",
  "god’s": "God’s",
  "gonedes": "Gonedes",
  "goodman": "Goodman",
  "google": "Google",
  "gordon": "Gordon",
  "gpss": "GPSS",
  "graham": "Graham",
  "grai": "GRAI",
  "graicunas": "Graicunas",
  "grammy": "Grammy",
  "granger": "Granger",
  "grant": "Grant",
  "grayson": "Grayson",
  "greece": "Greece",
  "green's": "Green's",
  "greer": "Greer",
  "gruber": "Gruber",
  "guillaume": "Guillaume",
  "guinea": "Guinea",
  "h": "H",
  "h1n1": "H1N1",
  "haar": "Haar",
  "haas": "Haas",
  "hahn's": "Hahn's",
  "hall": "Hall",
  "halloween": "Halloween",
  "hankel": "Hankel",
  "harold": "Harold",
  "harrod": "Harrod",
  "hatfield's": "Hatfield's",
  "hausman": "Hausman",
  "hawthorne": "Hawthorne",
  "hayek": "Hayek",
  "hebrew": "Hebrew",
  "heckscher": "Heckscher",
  "hegel": "Hegel",
  "heinrich": "Heinrich",
  "henry": "Henry",
  "herfindahl": "Herfindahl",
  "hermite": "Hermite",
  "hermitian": "Hermitian",
  "hfr": "Hfr",
  "hhgregg": "HHGregg",
  "hi": "HI",
  "hicks": "Hicks",
  "hicksian": "Hicksian",
  "hie": "HIE",
  "hilbert": "Hilbert",
  "hirschman": "Hirschman",
  "hispanic": "Hispanic",
  "hiv": "HIV",
  "hmo": "HMO",
  "holland": "Holland",
  "hollywood": "Hollywood",
  "holt": "Holt",
  "homo": "Homo",
  "hong": "Hong",
  "hotelling": "Hotelling",
  "houston": "Houston",
  "hov": "HOV",
  "hp": "HP",
  "hr": "HR",
  "hrm": "HRM",
  "huang": "Huang",
  "hume": "Hume",
  "hungarian": "Hungarian",
  "i'm": "I'm",
  "ie": "IE",
  "iie": "IIE",
  "ilgen": "Ilgen",
  "illinois": "Illinois",
  "im": "IM",
  "imf": "IMF",
  "inc": "Inc",
  "india": "India",
  "india's": "India's",
  "indian": "Indian",
  "indiana": "Indiana",
  "indonesia": "Indonesia",
  "indonesian": "Indonesian",
  "industry1": "Industry1",
  "institute": "Institute",
  "institute's": "Institute's",
  "intel": "Intel",
  "internet": "Internet",
  "ior": "IOR",
  "iowa": "Iowa",
  "ipma": "IPMA",
  "ipo": "IPO",
  "iq": "IQ",
  "iran": "Iran",
  "iranian": "Iranian",
  "irish": "Irish",
  "irr": "IRR",
  "irving": "Irving",
  "irwin": "Irwin",
  "ismail": "Ismail",
  "iso": "ISO",
  "israel": "Israel",
  "israel's": "Israel's",
  "israeli": "Israeli",
  "italian": "Italian",
  "italy": "Italy",
  "itc": "ITC",
  "iv": "IV",
  "ivf": "IVF",
  "ix": "IX",
  "i’ll": "I’ll",
  "j": "J",
  "jack": "Jack",
  "jackson": "Jackson",
  "jacobs'": "Jacobs'",
  "jai": "JAI",
  "jamaica": "Jamaica",
  "james": "James",
  "january": "January",
  "japan": "Japan",
  "japan's": "Japan's",
  "japanese": "Japanese",
  "java": "Java",
  "jcr": "JCR",
  "jdi": "JDI",
  "jeea": "JEEA",
  "jenkins": "Jenkins",
  "jersey": "Jersey",
  "jerusalem": "Jerusalem",
  "jevons": "Jevons",
  "jevons's": "Jevons's",
  "jewish": "Jewish",
  "jip": "JIP",
  "jit": "JIT",
  "jn": "JN",
  "jobcentre": "Jobcentre",
  "john": "John",
  "johnson": "Johnson",
  "johnston": "Johnston",
  "jones": "Jones",
  "jones's": "Jones's",
  "jordan": "Jordan",
  "journal": "Journal",
  "jr": "Jr",
  "jrc": "JRC",
  "jscm": "JSCM",
  "july": "July",
  "june": "June",
  "k12": "K12",
  "kaehler": "Kaehler",
  "kalecki": "Kalecki",
  "kalman": "Kalman",
  "kansas": "Kansas",
  "karasek's": "Karasek's",
  "katrina": "Katrina",
  "kennedy": "Kennedy",
  "kentucky": "Kentucky",
  "kenya": "Kenya",
  "kenyan": "Kenyan",
  "keynes": "Keynes",
  "keynes'": "Keynes'",
  "keynesian": "Keynesian",
  "keynesianism": "Keynesianism",
  "king": "King",
  "king's": "King's",
  "kingdom": "Kingdom",
  "klein": "Klein",
  "klein's": "Klein's",
  "knight": "Knight",
  "knight's": "Knight's",
  "kolb's": "Kolb's",
  "kolmogorov": "Kolmogorov",
  "kong": "Kong",
  "korea": "Korea",
  "korean": "Korean",
  "kruskal": "Kruskal",
  "kuiper": "Kuiper",
  "kumar": "Kumar",
  "kuznets": "Kuznets",
  "kähler": "Kähler",
  "l": "L",
  "l1": "L1",
  "l2": "L2",
  "laband": "Laband",
  "laffer": "Laffer",
  "lagerhaltung": "Lagerhaltung",
  "lagos": "Lagos",
  "lamarckian": "Lamarckian",
  "lankan": "Lankan",
  "laplace": "Laplace",
  "laplace's": "Laplace's",
  "larson": "Larson",
  "latin": "Latin",
  "lawrence": "Lawrence",
  "ldcs": "LDCs",
  "lee": "Lee",
  "leone": "Leone",
  "lerner": "Lerner",
  "lerner's": "Lerner's",
  "leviathan": "Leviathan",
  "levine": "Levine",
  "levitt": "Levitt",
  "liberia": "Liberia",
  "lidar": "LiDAR",
  "lifo": "LIFO",
  "lipsey": "Lipsey",
  "littleton's": "Littleton's",
  "littlewood": "Littlewood",
  "liv": "LIV",
  "livingston": "Livingston",
  "liz": "Liz",
  "lm": "LM",
  "london": "London",
  "lorenz": "Lorenz",
  "louderback": "Louderback",
  "louis": "Louis",
  "louisiana": "Louisiana",
  "lp": "LP",
  "lrd": "LRD",
  "lsb": "LSB",
  "lucas": "Lucas",
  "lufthansa": "Lufthansa",
  "lusin": "Lusin",
  "lx": "LX",
  "m0": "M0",
  "m1": "M1",
  "m12": "M12",
  "m13": "M13",
  "m2": "M2",
  "m3": "M3",
  "machina's": "Machina's",
  "madison": "Madison",
  "magellanic": "Magellanic",
  "maharashtra": "Maharashtra",
  "maine": "Maine",
  "malawi": "Malawi",
  "malaysia": "Malaysia",
  "malaysian": "Malaysian",
  "malcolm": "Malcolm",
  "malkiel": "Malkiel",
  "malthus": "Malthus",
  "malthusian": "Malthusian",
  "manova": "MANOVA",
  "march": "March",
  "marion": "Marion",
  "markoff": "Markoff",
  "markov": "Markov",
  "markovian": "Markovian",
  "markowitz": "Markowitz",
  "mars": "Mars",
  "marshall": "Marshall",
  "marshall's": "Marshall's",
  "mart": "Mart",
  "martin": "Martin",
  "marx": "Marx",
  "massachusetts": "Massachusetts",
  "maxwell": "Maxwell",
  "may's": "May's",
  "maya": "Maya",
  "mayer": "Mayer",
  "mba": "MBA",
  "mbo": "MBO",
  "mec": "MEC",
  "medicaid": "Medicaid",
  "medicare": "Medicare",
  "mediterranean": "Mediterranean",
  "meese": "Meese",
  "meiji": "Meiji",
  "meiselman": "Meiselman",
  "meltzer": "Meltzer",
  "mem": "MEM",
  "mendelian": "Mendelian",
  "menger": "Menger",
  "merced": "Merced",
  "mercosur": "MERCOSUR",
  "mesopotamia": "Mesopotamia",
  "methodist": "Methodist",
  "metzler": "Metzler",
  "mexican": "Mexican",
  "mexico": "Mexico",
  "miami": "Miami",
  "michal": "Michal",
  "michigan": "Michigan",
  "mickey": "Mickey",
  "microsystems": "Microsystems",
  "mideast": "Mideast",
  "midlands": "Midlands",
  "midwest": "Midwest",
  "mill's": "Mill's",
  "miller": "Miller",
  "miller's": "Miller's",
  "milton": "Milton",
  "mincer's": "Mincer's",
  "minnesota": "Minnesota",
  "mis": "MIS",
  "mit": "MIT",
  "mnc": "MNC",
  "modigliani": "Modigliani",
  "moe": "MoE",
  "monte": "Monte",
  "monty": "Monty",
  "moore": "Moore",
  "morgan": "Morgan",
  "morgenstern": "Morgenstern",
  "morishima": "Morishima",
  "morocco": "Morocco",
  "morse": "Morse",
  "mph": "MPH",
  "mr": "Mr",
  "mrp": "MRP",
  "ms": "MS",
  "ms2": "MS2",
  "muslim": "Muslim",
  "mustard": "MUStARD",
  "muthian": "Muthian",
  "nairobi": "Nairobi",
  "nairu": "NAIRU",
  "napster": "Napster",
  "nasdaq": "Nasdaq",
  "nash": "Nash",
  "nato": "NATO",
  "navajo": "Navajo",
  "navy": "Navy",
  "nazi": "Nazi",
  "nba": "NBA",
  "ncaa": "NCAA",
  "nebraska": "Nebraska",
  "negro": "Negro",
  "neolithic": "Neolithic",
  "nepal": "Nepal",
  "netherlands": "Netherlands",
  "neumann": "Neumann",
  "neumann's": "Neumann's",
  "neurospora": "Neurospora",
  "nevada": "Nevada",
  "nfl": "NFL",
  "nic": "NIC",
  "nicholas": "Nicholas",
  "nicholson": "Nicholson",
  "nigeria": "Nigeria",
  "nlsy": "NLSY",
  "noetherian": "Noetherian",
  "north": "North",
  "northwest": "Northwest",
  "norway": "Norway",
  "norwegian": "Norwegian",
  "november": "November",
  "nra": "NRA",
  "nsf": "NSF",
  "nyse": "NYSE",
  "o": "O",
  "obituary": "Obituary",
  "ocs": "OCS",
  "october": "October",
  "od": "OD",
  "oecd": "OECD",
  "ohio": "Ohio",
  "ohlin": "Ohlin",
  "oi's": "Oi's",
  "olg": "OLG",
  "olympics": "Olympics",
  "om": "OM",
  "oncorhynchus": "Oncorhynchus",
  "onsager": "Onsager",
  "opa": "OPA",
  "opec": "OPEC",
  "orcutt": "Orcutt",
  "orleans": "Orleans",
  "orr": "ORR",
  "otc": "OTC",
  "oxford": "Oxford",
  "oxley": "Oxley",
  "p's": "P's",
  "p2": "P2",
  "p22": "P22",
  "pacific": "Pacific",
  "pacioli": "Pacioli",
  "paciolo": "Paciolo",
  "pakistan": "Pakistan",
  "pakistan's": "Pakistan's",
  "paley": "Paley",
  "paramecium": "Paramecium",
  "paretian": "Paretian",
  "pareto": "Pareto",
  "parkin": "Parkin",
  "patinkin": "Patinkin",
  "patman": "Patman",
  "pc": "PC",
  "peltzman": "Peltzman",
  "penn": "Penn",
  "pennsylvania": "Pennsylvania",
  "periodicals": "Periodicals",
  "pert": "PERT",
  "peruvian": "Peruvian",
  "peter": "Peter",
  "peters": "Peters",
  "petersburg": "Petersburg",
  "pfaffian": "Pfaffian",
  "pga": "PGA",
  "ph": "Ph",
  "phds": "PhDs",
  "philadelphia": "Philadelphia",
  "philippine": "Philippine",
  "philippines": "Philippines",
  "phillips": "Phillips",
  "picard": "Picard",
  "pigou": "Pigou",
  "pigovian": "Pigovian",
  "piketty": "Piketty",
  "pipa": "PIPA",
  "pittsburgh": "Pittsburgh",
  "pl": "PL",
  "plasm": "Plasm",
  "pleistocene": "Pleistocene",
  "pm2": "PM2",
  "poisson": "Poisson",
  "polish": "Polish",
  "pom": "POM",
  "poor's": "Poor's",
  "porter's": "Porter's",
  "pos": "POS",
  "ppp": "PPP",
  "pradesh": "Pradesh",
  "prandtl": "Prandtl",
  "president's": "President's",
  "press": "Press",
  "preston": "Preston",
  "proceedings": "Proceedings",
  "progresa": "PROGRESA",
  "protestant": "Protestant",
  "protestantism": "Protestantism",
  "prussia": "Prussia",
  "puerto": "Puerto",
  "punjab": "Punjab",
  "q4": "Q4",
  "qfd": "QFD",
  "r": "R",
  "r17": "R17",
  "r2": "R2",
  "radcliffe": "Radcliffe",
  "ramadan": "Ramadan",
  "raman": "Raman",
  "ramsey": "Ramsey",
  "ras": "RAs",
  "rawls'": "Rawls'",
  "rawlsian": "Rawlsian",
  "rees": "Rees",
  "reno": "Reno",
  "republic": "Republic",
  "res": "Res",
  "reserve's": "Reserve's",
  "reynolds": "Reynolds",
  "rfid": "RFID",
  "rhode": "Rhode",
  "rhodospirillum": "Rhodospirillum",
  "ricardian": "Ricardian",
  "ricardo": "Ricardo",
  "ricci": "Ricci",
  "richard": "Richard",
  "rico": "Rico",
  "riemann": "Riemann",
  "riemannian": "Riemannian",
  "rizzo's": "Rizzo's",
  "rna": "RNA",
  "robinson": "Robinson",
  "roch": "Roch",
  "rockefeller": "Rockefeller",
  "roe": "ROE",
  "roegen": "Roegen",
  "rogoff": "Rogoff",
  "rohm": "Rohm",
  "rome": "Rome",
  "romer": "Romer",
  "rosa": "Rosa",
  "rosen's": "Rosen's",
  "rotemberg": "Rotemberg",
  "roy": "Roy",
  "royal": "Royal",
  "rs": "RS",
  "rsm": "RSM",
  "rumelt's": "Rumelt's",
  "russia": "Russia",
  "russia's": "Russia's",
  "russian": "Russian",
  "rust": "Rust",
  "s2": "S2",
  "saharan": "Saharan",
  "salamon": "Salamon",
  "salancik's": "Salancik's",
  "salmo": "Salmo",
  "salmonella": "Salmonella",
  "samaritan's": "Samaritan's",
  "samuelson": "Samuelson",
  "samuelson's": "Samuelson's",
  "san": "San",
  "santa": "Santa",
  "sarbanes": "Sarbanes",
  "sb1070": "SB1070",
  "sbu": "SBU",
  "scandinavian": "Scandinavian",
  "scat": "SCAT",
  "schmenner's": "Schmenner's",
  "schon's": "Schon's",
  "schultz": "Schultz",
  "schumpeter": "Schumpeter",
  "schumpeter's": "Schumpeter's",
  "scjm": "SCJM",
  "scm": "SCM",
  "scm's": "SCM's",
  "scotland": "Scotland",
  "scott": "Scott",
  "scottish": "Scottish",
  "scully": "Scully",
  "scylla": "Scylla",
  "sec": "SEC",
  "sed": "SED",
  "sematech": "SEMATECH",
  "senate": "Senate",
  "sentinel": "Sentinel",
  "september": "September",
  "serm": "SERM",
  "ses": "SES",
  "sesame": "Sesame",
  "sez": "SEZ",
  "sezs": "SEZs",
  "shakespeare": "Shakespeare",
  "shapira": "Shapira",
  "sharpe": "Sharpe",
  "shenzhen": "Shenzhen",
  "sherman": "Sherman",
  "shewhart": "Shewhart",
  "shi": "Shi",
  "siegel": "Siegel",
  "siemens": "Siemens",
  "sierra": "Sierra",
  "silber": "Silber",
  "simon": "Simon",
  "singapore": "Singapore",
  "sioux": "Sioux",
  "skinner": "Skinner",
  "sku": "SKU",
  "slichter": "Slichter",
  "slutsky": "Slutsky",
  "smith": "Smith",
  "smith's": "Smith's",
  "smith’s": "Smith’s",
  "smj": "SMJ",
  "snap": "SNAP",
  "snow's": "Snow's",
  "soda": "SODA",
  "soe": "SOE",
  "solow": "Solow",
  "somali": "Somali",
  "somalia": "Somalia",
  "sons": "Sons",
  "sopa": "SOPA",
  "soup's": "Soup's",
  "south": "South",
  "southeast": "Southeast",
  "soviet": "Soviet",
  "sp": "SP",
  "spain": "Spain",
  "spanish": "Spanish",
  "spat": "SPAT",
  "spence": "Spence",
  "sperner's": "Sperner's",
  "squire": "Squire",
  "sri": "Sri",
  "st": "St",
  "stackelberg": "Stackelberg",
  "stafford": "Stafford",
  "stanford": "Stanford",
  "stanley": "Stanley",
  "statistische": "Statistische",
  "statler": "Statler",
  "sterling's": "Sterling's",
  "steven": "Steven",
  "stiefel": "Stiefel",
  "stigler": "Stigler",
  "stirling": "Stirling",
  "stockman": "Stockman",
  "streptomyces": "Streptomyces",
  "stud": "Stud",
  "sudan": "Sudan",
  "sun": "Sun",
  "supreme": "Supreme",
  "sv": "SV",
  "sv40": "SV40",
  "svar": "SVAR",
  "sweden": "Sweden",
  "sweden's": "Sweden's",
  "swedish": "Swedish",
  "swiss": "Swiss",
  "switzerland": "Switzerland",
  "sylow": "Sylow",
  "t2": "T2",
  "t3": "T3",
  "t4": "T4",
  "t5": "T5",
  "taguchi": "Taguchi",
  "taiwan": "Taiwan",
  "taiwan's": "Taiwan's",
  "taiwanese": "Taiwanese",
  "tamara": "Tamara",
  "tanzania": "Tanzania",
  "tanzanian": "Tanzanian",
  "tarp": "TARP",
  "tattershall": "Tattershall",
  "taylor": "Taylor",
  "taylor's": "Taylor's",
  "tcp": "TCP",
  "terborgh's": "Terborgh's",
  "tetrahymena": "Tetrahymena",
  "texas": "Texas",
  "tfp": "TFP",
  "thailand": "Thailand",
  "theory1": "Theory1",
  "thorstein": "Thorstein",
  "tic": "TIC",
  "tims": "TIMS",
  "tk": "TK",
  "tm": "TM",
  "tobin": "Tobin",
  "toc": "TOC",
  "toe": "TOE",
  "tokyo": "Tokyo",
  "tollison": "Tollison",
  "toronto": "Toronto",
  "tpm": "TPM",
  "tqm": "TQM",
  "treasury": "Treasury",
  "triassic": "Triassic",
  "trident": "Trident",
  "triffin": "Triffin",
  "triffin's": "Triffin's",
  "tullock": "Tullock",
  "tullock's": "Tullock's",
  "turkey": "Turkey",
  "turkey’s": "Turkey’s",
  "turkish": "Turkish",
  "tv": "TV",
  "tva": "TVA",
  "tylenol": "Tylenol",
  "u": "U",
  "uc": "UC",
  "uefa": "UEFA",
  "uganda": "Uganda",
  "uk": "UK",
  "ukraine": "Ukraine",
  "ultramares": "Ultramares",
  "underwood": "Underwood",
  "united": "United",
  "university": "University",
  "uruguay": "Uruguay",
  "urwick": "Urwick",
  "usa": "USA",
  "usda": "USDA",
  "va": "VA",
  "vancouver": "Vancouver",
  "var": "VAR",
  "vars": "VARs",
  "vat": "VAT",
  "veblen's": "Veblen's",
  "vi": "VI",
  "vietnam": "Vietnam",
  "vii": "VII",
  "viii": "VIII",
  "virginia": "Virginia",
  "vm": "VM",
  "vogel": "Vogel",
  "voigt": "Voigt",
  "volvo": "Volvo",
  "vroom": "Vroom",
  "vytautas": "Vytautas",
  "w": "W",
  "wade": "Wade",
  "wagner": "Wagner",
  "wal": "Wal",
  "wales": "Wales",
  "walker's": "Walker's",
  "waller": "Waller",
  "wallingford": "Wallingford",
  "wallis": "Wallis",
  "walras": "Walras",
  "walsh": "Walsh",
  "walter": "Walter",
  "wams": "WAMs",
  "wang": "Wang",
  "washington": "Washington",
  "watergate": "Watergate",
  "weai": "WEAI",
  "weber": "Weber",
  "weierstrass": "Weierstrass",
  "weiss": "Weiss",
  "wellesley": "Wellesley",
  "west": "West",
  "western": "Western",
  "weston": "Weston",
  "wharton": "Wharton",
  "where's": "Where's",
  "whitin": "Whitin",
  "whitney": "Whitney",
  "wic": "WIC",
  "wiener": "Wiener",
  "wiles": "Wiles",
  "wisconsin": "Wisconsin",
  "wolfe's": "Wolfe's",
  "woodward": "Woodward",
  "woodward's": "Woodward's",
  "wright's": "Wright's",
  "wto": "WTO",
  "xl": "XL",
  "xlii": "XLII",
  "xlix": "XLIX",
  "xlvi": "XLVI",
  "xxix": "XXIX",
  "xxviii": "XXVIII",
  "xxxix": "XXXIX",
  "xxxvi": "XXXVI",
  "xxxvii": "XXXVII",
  "yale": "Yale",
  "yang": "Yang",
  "yellowstone": "Yellowstone",
  "yetton": "Yetton",
  "yilmaz": "Yilmaz",
  "york": "York",
  "youtube": "YouTube",
  "yugoslav": "Yugoslav",
  "zariski": "Zariski",
  "zea": "Zea",
  "zealand": "Zealand",
  "zhou": "Zhou",
  "ziegler": "Ziegler",
  "zimbabwe": "Zimbabwe",
  "zmud": "Zmud",
};

// lowercase multi-word run -> the form to restore. Needed because the parts are
// lowercase-dominant on their own ("states", "york", "war"), so word-by-word
// restoration would give "United states".
export const TITLECASE_PHRASES = {
  "accountants association": "Accountants Association",
  "accounting association": "Accounting Association",
  "accounting association's": "Accounting Association's",
  "accounting committee": "Accounting Committee",
  "accounting research bulletin": "Accounting Research Bulletin",
  "accounting review": "Accounting Review",
  "accounting trends": "Accounting Trends",
  "affordable care": "Affordable Care",
  "affordable care act": "Affordable Care Act",
  "air act": "Air Act",
  "air force": "Air Force",
  "akron brass": "Akron Brass",
  "akron brass manufacturing": "Akron Brass Manufacturing",
  "alaska permanent": "Alaska Permanent",
  "alaska permanent fund": "Alaska Permanent Fund",
  "american accounting": "American Accounting",
  "american accounting association": "American Accounting Association",
  "american accounting association's": "American Accounting Association's",
  "american association": "American Association",
  "american business": "American Business",
  "american dream": "American Dream",
  "american economic": "American Economic",
  "american economic association": "American Economic Association",
  "american economy": "American Economy",
  "american finance": "American Finance",
  "american finance association": "American Finance Association",
  "american health": "American Health",
  "american life": "American Life",
  "american productivity": "American Productivity",
  "american public": "American Public",
  "american society": "American Society",
  "american states": "American States",
  "american telephone": "American Telephone",
  "american trade": "American Trade",
  "angeles county": "Angeles County",
  "annual meeting american": "Annual Meeting American",
  "applied organization": "Applied Organization",
  "applied organization analysis": "Applied Organization Analysis",
  "arab spring": "Arab Spring",
  "army audit": "Army Audit",
  "army audit agency": "Army Audit Agency",
  "associated press": "Associated Press",
  "association annual": "Association Annual",
  "association annual meeting": "Association Annual Meeting",
  "atlantic ocean": "Atlantic Ocean",
  "audit agency": "Audit Agency",
  "auditing laboratory": "Auditing Laboratory",
  "baldrige award": "Baldrige Award",
  "baldrige national": "Baldrige National",
  "baldrige national quality": "Baldrige National Quality",
  "bankers association": "Bankers Association",
  "baseball hall": "Baseball Hall",
  "basketball association": "Basketball Association",
  "bay area": "Bay Area",
  "bayesian additive": "Bayesian Additive",
  "bayesian model averaging": "Bayesian Model Averaging",
  "bayesian persuasion": "Bayesian Persuasion",
  "bayesian statistics": "Bayesian Statistics",
  "best paper award": "Best Paper Award",
  "best paper prize": "Best Paper Prize",
  "black americans": "Black Americans",
  "black hispanic": "Black Hispanic",
  "blue cross": "Blue Cross",
  "blue shield": "Blue Shield",
  "book notes": "Book Notes",
  "books received": "Books Received",
  "box cox": "Box Cox",
  "box jenkins": "Box Jenkins",
  "brass manufacturing": "Brass Manufacturing",
  "brief case game": "Brief Case Game",
  "british accounting": "British Accounting",
  "british gas": "British Gas",
  "british industrial": "British Industrial",
  "british industry": "British Industry",
  "british telecom": "British Telecom",
  "brothers inc": "Brothers Inc",
  "business logistics": "Business Logistics",
  "canadian dollar": "Canadian Dollar",
  "canadian national": "Canadian National",
  "care act": "Care Act",
  "case game": "Case Game",
  "central america": "Central America",
  "central american": "Central American",
  "central statistical": "Central Statistical",
  "central statistical office": "Central Statistical Office",
  "centrifugal pipe": "Centrifugal Pipe",
  "champions league": "Champions League",
  "channel islands": "Channel Islands",
  "chartered financial": "Chartered Financial",
  "chartered financial analysts": "Chartered Financial Analysts",
  "citation reports": "Citation Reports",
  "clean air act": "Clean Air Act",
  "coase theorem": "Coase Theorem",
  "commerce commission": "Commerce Commission",
  "companies act": "Companies Act",
  "company inc": "Company Inc",
  "company program": "Company Program",
  "completion scale": "Completion Scale",
  "consumer finances": "Consumer Finances",
  "continental europe": "Continental Europe",
  "control act": "Control Act",
  "controllers institute": "Controllers Institute",
  "corporate average": "Corporate Average",
  "corporate average fuel": "Corporate Average Fuel",
  "cost accounting concepts": "Cost Accounting Concepts",
  "county california": "County California",
  "county indiana": "County Indiana",
  "current topics": "Current Topics",
  "decade award": "Decade Award",
  "decision sciences journal": "Decision Sciences Journal",
  "descriptive index": "Descriptive Index",
  "dickey fuller": "Dickey Fuller",
  "earnings survey": "Earnings Survey",
  "eastern europe": "Eastern Europe",
  "eastern finance": "Eastern Finance",
  "eastern finance association": "Eastern Finance Association",
  "economic association": "Economic Association",
  "economic inquiry": "Economic Inquiry",
  "economic journal": "Economic Journal",
  "economic journal volume": "Economic Journal Volume",
  "economic review": "Economic Review",
  "edison company": "Edison Company",
  "editor's comments": "Editor's Comments",
  "education university": "Education University",
  "eighth annual": "Eighth Annual",
  "eighth annual meeting": "Eighth Annual Meeting",
  "environmental kuznets": "Environmental Kuznets",
  "environmental kuznets curve": "Environmental Kuznets Curve",
  "estate finance": "Estate Finance",
  "euro dollar market": "Euro Dollar Market",
  "european central": "European Central",
  "european central bank": "European Central Bank",
  "european finance": "European Finance",
  "european finance association": "European Finance Association",
  "european manufacturing": "European Manufacturing",
  "european monetary": "European Monetary",
  "european monetary system": "European Monetary System",
  "european monetary union": "European Monetary Union",
  "european union": "European Union",
  "exchange commission": "Exchange Commission",
  "expenditure survey": "Expenditure Survey",
  "faculty fellowship": "Faculty Fellowship",
  "family expenditure survey": "Family Expenditure Survey",
  "far east": "Far East",
  "federal credit": "Federal Credit",
  "federal government accountants": "Federal Government Accountants",
  "federal home": "Federal Home",
  "federal home loan": "Federal Home Loan",
  "federal housing administration": "Federal Housing Administration",
  "federal income taxation": "Federal Income Taxation",
  "federal national mortgage": "Federal National Mortgage",
  "federal open": "Federal Open",
  "federal open market": "Federal Open Market",
  "federal power": "Federal Power",
  "federal power commission": "Federal Power Commission",
  "federal reserve": "Federal Reserve",
  "federal reserve bank": "Federal Reserve Bank",
  "federal reserve board": "Federal Reserve Board",
  "federal reserve district": "Federal Reserve District",
  "federal reserve system": "Federal Reserve System",
  "federal reserve's": "Federal Reserve's",
  "fifth annual meeting": "Fifth Annual Meeting",
  "fifty fifth": "Fifty Fifth",
  "fifty fifth annual": "Fifty Fifth Annual",
  "finance association": "Finance Association",
  "finance corporation": "Finance Corporation",
  "financial management association": "Financial Management Association",
  "first annual meeting": "First Annual Meeting",
  "football league": "Football League",
  "forest service": "Forest Service",
  "fortieth annual": "Fortieth Annual",
  "fortieth annual meeting": "Fortieth Annual Meeting",
  "forty fifth": "Forty Fifth",
  "forty fifth annual": "Forty Fifth Annual",
  "forty first": "Forty First",
  "forty first annual": "Forty First Annual",
  "forty second": "Forty Second",
  "forty second annual": "Forty Second Annual",
  "forty seventh": "Forty Seventh",
  "forty seventh annual": "Forty Seventh Annual",
  "foundation research": "Foundation Research",
  "fourth annual": "Fourth Annual",
  "fourth annual meeting": "Fourth Annual Meeting",
  "francisco bay": "Francisco Bay",
  "francisco bay area": "Francisco Bay Area",
  "french revolution": "French Revolution",
  "general motors": "General Motors",
  "general research": "General Research",
  "german federal": "German Federal",
  "gibrat's law": "Gibrat's Law",
  "gimbel brothers": "Gimbel Brothers",
  "gimbel brothers inc": "Gimbel Brothers Inc",
  "government accountants": "Government Accountants",
  "government accountants association": "Government Accountants Association",
  "great britain": "Great Britain",
  "great contraction": "Great Contraction",
  "great depression": "Great Depression",
  "great recession": "Great Recession",
  "health act": "Health Act",
  "herfindahl hirschman index": "Herfindahl Hirschman Index",
  "hidden markov": "Hidden Markov",
  "hidden markov model": "Hidden Markov Model",
  "hilbert space": "Hilbert Space",
  "hirschman index": "Hirschman Index",
  "hockey league": "Hockey League",
  "home loan bank": "Home Loan Bank",
  "horizontal merger guidelines": "Horizontal Merger Guidelines",
  "housing administration": "Housing Administration",
  "hurricane katrina": "Hurricane Katrina",
  "institute research": "Institute Research",
  "institute research foundation": "Institute Research Foundation",
  "internal revenue": "Internal Revenue",
  "internal revenue code": "Internal Revenue Code",
  "internal revenue service": "Internal Revenue Service",
  "international congress": "International Congress",
  "international economic review": "International Economic Review",
  "international salt": "International Salt",
  "interstate commerce commission": "Interstate Commerce Commission",
  "investment company act": "Investment Company Act",
  "irwin friend": "Irwin Friend",
  "job corps": "Job Corps",
  "job descriptive": "Job Descriptive",
  "job descriptive index": "Job Descriptive Index",
  "journal citation reports": "Journal Citation Reports",
  "journal volume": "Journal Volume",
  "kalman filter": "Kalman Filter",
  "keynesian phillips curve": "Keynesian Phillips Curve",
  "korean war": "Korean War",
  "kuznets curve": "Kuznets Curve",
  "laplace approximation": "Laplace Approximation",
  "late pleistocene": "Late Pleistocene",
  "loan bank": "Loan Bank",
  "loan bank system": "Loan Bank System",
  "london stock": "London Stock",
  "los angeles": "Los Angeles",
  "los angeles county": "Los Angeles County",
  "magellanic clouds": "Magellanic Clouds",
  "mainland china": "Mainland China",
  "malcolm baldrige national": "Malcolm Baldrige National",
  "management association": "Management Association",
  "management journal": "Management Journal",
  "march madness": "March Madness",
  "market committee": "Market Committee",
  "markov chain": "Markov Chain",
  "markov decision": "Markov Decision",
  "markov decision process": "Markov Decision Process",
  "markov decision processes": "Markov Decision Processes",
  "markov model": "Markov Model",
  "markov process": "Markov Process",
  "marshall plan": "Marshall Plan",
  "medicare part": "Medicare Part",
  "meeting american": "Meeting American",
  "meeting american finance": "Meeting American Finance",
  "merger guidelines": "Merger Guidelines",
  "metropolitan edison": "Metropolitan Edison",
  "michigan state": "Michigan State",
  "michigan state university": "Michigan State University",
  "middle east": "Middle East",
  "miner sentence": "Miner Sentence",
  "miner sentence completion": "Miner Sentence Completion",
  "modern internal": "Modern Internal",
  "modern internal auditing": "Modern Internal Auditing",
  "mortgage association": "Mortgage Association",
  "nash equilibrium": "Nash Equilibrium",
  "national academy": "National Academy",
  "national association": "National Association",
  "national basketball": "National Basketball",
  "national basketball association": "National Basketball Association",
  "national board": "National Board",
  "national bureau": "National Bureau",
  "national coal": "National Coal",
  "national football": "National Football",
  "national football league": "National Football League",
  "national health service": "National Health Service",
  "national hockey": "National Hockey",
  "national hockey league": "National Hockey League",
  "national job": "National Job",
  "national mortgage association": "National Mortgage Association",
  "national quality award": "National Quality Award",
  "neo austrian": "Neo Austrian",
  "ninth annual": "Ninth Annual",
  "ninth annual meeting": "Ninth Annual Meeting",
  "north atlantic ocean": "North Atlantic Ocean",
  "ohio state": "Ohio State",
  "ohio state university": "Ohio State University",
  "open market committee": "Open Market Committee",
  "operation twist": "Operation Twist",
  "opportunity act": "Opportunity Act",
  "organizations survey": "Organizations Survey",
  "oxley act": "Oxley Act",
  "paper award": "Paper Award",
  "paper prize": "Paper Prize",
  "partnership act": "Partnership Act",
  "patman act": "Patman Act",
  "people's republic": "People's Republic",
  "permanent fund": "Permanent Fund",
  "peter principle": "Peter Principle",
  "phillips curve": "Phillips Curve",
  "planning programming budgeting": "Planning Programming Budgeting",
  "population survey": "Population Survey",
  "post world": "Post World",
  "power commission": "Power Commission",
  "premium pension": "Premium Pension",
  "proceedings fifty": "Proceedings Fifty",
  "quarterly information": "Quarterly Information",
  "rating committee": "Rating Committee",
  "reform act": "Reform Act",
  "regulatory commission": "Regulatory Commission",
  "relief act": "Relief Act",
  "research bulletin": "Research Bulletin",
  "research foundation": "Research Foundation",
  "research grants": "Research Grants",
  "reserve bank": "Reserve Bank",
  "reserve board": "Reserve Board",
  "reserve district": "Reserve District",
  "revenue act": "Revenue Act",
  "revenue service": "Revenue Service",
  "rhode island": "Rhode Island",
  "ricardian equivalence": "Ricardian Equivalence",
  "ricardian equivalence theorem": "Ricardian Equivalence Theorem",
  "robinson patman act": "Robinson Patman Act",
  "rockefeller foundation": "Rockefeller Foundation",
  "royal commission": "Royal Commission",
  "rust belt": "Rust Belt",
  "san francisco bay": "San Francisco Bay",
  "sarbanes oxley act": "Sarbanes Oxley Act",
  "sciences journal": "Sciences Journal",
  "second annual meeting": "Second Annual Meeting",
  "securities act": "Securities Act",
  "security administration": "Security Administration",
  "sentence completion scale": "Sentence Completion Scale",
  "sequential monte": "Sequential Monte",
  "sequential monte carlo": "Sequential Monte Carlo",
  "service operations management": "Service Operations Management",
  "session topic": "Session Topic",
  "seventh annual": "Seventh Annual",
  "seventh annual meeting": "Seventh Annual Meeting",
  "sherman act": "Sherman Act",
  "sino japanese": "Sino Japanese",
  "social security administration": "Social Security Administration",
  "software reviews": "Software Reviews",
  "southern methodist": "Southern Methodist",
  "southern methodist university": "Southern Methodist University",
  "soviet union": "Soviet Union",
  "standards rating": "Standards Rating",
  "standards rating committee": "Standards Rating Committee",
  "standards underlying corporate": "Standards Underlying Corporate",
  "state street": "State Street",
  "state university": "State University",
  "states canada": "States Canada",
  "states china": "States China",
  "states economic": "States Economic",
  "states government": "States Government",
  "states japan": "States Japan",
  "states navy": "States Navy",
  "states senate": "States Senate",
  "states steel": "States Steel",
  "states supreme": "States Supreme",
  "states supreme court": "States Supreme Court",
  "states treasury": "States Treasury",
  "states united": "States United",
  "states united kingdom": "States United Kingdom",
  "steel corporation": "Steel Corporation",
  "sub saharan": "Sub Saharan",
  "sub saharan africa": "Sub Saharan Africa",
  "supreme court": "Supreme Court",
  "taiwan stock": "Taiwan Stock",
  "tax court": "Tax Court",
  "tax reform act": "Tax Reform Act",
  "taxpayer relief": "Taxpayer Relief",
  "taxpayer relief act": "Taxpayer Relief Act",
  "thesis titles": "Thesis Titles",
  "thirty eighth": "Thirty Eighth",
  "thirty eighth annual": "Thirty Eighth Annual",
  "thirty ninth": "Thirty Ninth",
  "thirty ninth annual": "Thirty Ninth Annual",
  "tokyo round": "Tokyo Round",
  "tokyo stock": "Tokyo Stock",
  "tokyo stock exchange": "Tokyo Stock Exchange",
  "toxics release": "Toxics Release",
  "toxics release inventory": "Toxics Release Inventory",
  "trade organization": "Trade Organization",
  "understanding society": "Understanding Society",
  "uniform certified": "Uniform Certified",
  "uniform certified public": "Uniform Certified Public",
  "united nations": "United Nations",
  "united states": "United States",
  "united states canada": "United States Canada",
  "united states china": "United States China",
  "united states economic": "United States Economic",
  "united states government": "United States Government",
  "united states international": "United States International",
  "united states japan": "United States Japan",
  "united states navy": "United States Navy",
  "united states senate": "United States Senate",
  "united states steel": "United States Steel",
  "united states supreme": "United States Supreme",
  "united states treasury": "United States Treasury",
  "united states united": "United States United",
  "university instructors": "University Instructors",
  "vietnam war": "Vietnam War",
  "von neumann": "Von Neumann",
  "von neumann morgenstern": "Von Neumann Morgenstern",
  "war department": "War Department",
  "washington state": "Washington State",
  "western finance": "Western Finance",
  "western finance association": "Western Finance Association",
  "wharton school": "Wharton School",
  "women infants": "Women Infants",
  "world bank": "World Bank",
  "world cup": "World Cup",
  "world trade organization": "World Trade Organization",
  "world war": "World War",
  "york city": "York City",
  "york state": "York State",
  "york stock": "York Stock",
  "york stock exchange": "York Stock Exchange",
  "young eyes": "Young Eyes",
};
